### ISSUE TITLE
Please create a new release containing latest fixes

### ISSUE THREAD

**Issue by k00ni** [pietercolpaert/hardf#15]
Otherwise i have to use "dev-master" to include your repository via composer.

Please include #16

**Comment by pietercolpaert** [comment]
Done! Sorry for late response!

**Comment by pietercolpaert** [comment]
In order to not slow your development process down, I’ve added you as a collaborator to this repository. Please still use the same cycle: pull request to development, only merge when the travis-ci builds, then pull from development to master and publish a release. If I see the pull request in time, I will still check it out myself.

I also added you as a collaborator on packagist. Don’t know if it’s important, yet the  bus factor of the project is now 2 instead of 1 ;)

**Comment by k00ni** [comment]
@pietercolpaert, first, thanks for merging these pull requests. And i am honored that you gave me these collaborator rights! 

> Please still use the same cycle: pull request to development, only merge when the travis-ci builds, then pull from development to master and publish a release. 

No problem, i think this way everybody can participate and new code can be discussed before merging. :+1:
