### ISSUE TITLE
results table

### ISSUE THREAD

**Issue by moissinac** [pietercolpaert/hardf#8]
Having the same memory footprint for 2K triples and 4M triples seems strange. How is it possible?

**Comment by pietercolpaert** [comment]
We read the turtle file streamingly instead of loading the file entirely in memory. We each team read a chunk, parse that, return triples, clear memory, continue parsing, etc. The only thing that is kept in memory are the prefixes and an entire literal, so the memory consumption could raise when large literals are given or when a lot of prefixes are used.
